# Generated by Django 4.2.13 on 2024-07-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AlterField(
            model_name='profile',
            name='nominated_bank_account',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
