# Generated by Django 4.2.13 on 2024-07-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0002_remove_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nominated_bank_account',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
