# Generated by Django 4.2.13 on 2024-07-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0005_remove_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
