# Generated by Django 4.2.13 on 2024-07-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0006_remove_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingpot',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
