# Generated by Django 4.2.13 on 2024-07-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0007_alter_savingpot_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True),
        ),
    ]
