# Generated by Django 4.2.13 on 2024-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0008_profile_age_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingpot',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
