# Generated by Django 4.2.13 on 2024-09-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0009_alter_savingpot_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
